config/routes.rb
Rails.application.routes.draw do
  root 'blog#index'
  resources :blog, except: [:new]
  get 'blogs/new' => 'blog#new', as: 'new_blog'
  
  get 'blogs/:id/edit' => 'blog#edit'
  delete 'blogs/:id' => 'blog#destroy'
  patch 'blogs/:id' => 'blog#update'
  get 'blogs/:id' => 'blog#show'
  post 'blogs' => 'blog#create'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog.rb
class Blog < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blog_controller.rb
class BlogController < ApplicationController
def index 
    @blogs = Blog.all 
end 
    
def show 
    @blog = Blog.find(params[:id])
end
    
def new 
    @blog = Blog.new
end

def edit
    @blog = Blog.find(params[:id])
end
    
def update
    @blog = Blog.find(params[:id])
    if @blog.update(blog_params)
      redirect_to root_path 
    else
      render :edit
    end
  end

def create 
  @blog = Blog.create(blog_params)
    if @blog.save
        redirect_to root_path
    else
        render :new
    end
end



def destroy 
    @blog = Blog.find(params[:id])
        if @blog.destroy
          redirect_to root_path
        else
          redirect_to root_path
        end
end
      
    
private 
def blog_params 
    params.require(:blog).permit(:title, :content)
end 

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_helper.rb
module BlogHelper
end

app/views/blog/edit.html.erb
<%= link_to 'Back to Home Page', '/' %>

<h2> EDIT </h2>
<%= form_with model: @blog, method: :patch do |form| %>

    <%= form.label :title %>
    <%= form.text_field :title %>

    <br>
    <%= form.label :content %>
    <%= form.text_field :content %>

    <br>
    <%= form.submit 'EDIT' %>
  <% end %>

app/views/blog/index.html.erb
<h1>BLOG TITLE</h1>

<ul>
    <% @blogs.each do |blog| %>
        <li><%= blog.title %> 
         <%= link_to 'SEE MORE', blog_path(blog) %>  
        </li>
    <% end %>
</ul>

<%= link_to 'ADD NEW', new_blog_path %>



<footer style="position: fixed; bottom: 0; width: 100%; text-align: center; background-color: #f0f0f0;">App create by <a href="https://www.linkedin.com/in/alejandra-hale/" target="_blank">Aleja</a> & <a href="https://www.linkedin.com/in/andrea-lopez-delgado/" target="_blank">Dre</a></footer>

app/views/blog/new.html.erb
<%= link_to 'Back to Home Page', '/' %>

<h2> ADD NEW </h2>
<%= form_with model: @blog do |form| %>

    <%= form.label :title %>
    <%= form.text_field :title %>

    <br>
    <%= form.label :content %>
    <%= form.text_field :content %>

    <br>
    <%= form.submit 'ADD NEW' %>
  <% end %>

app/views/blog/show.html.erb
<%= link_to 'Back to Home Page', '/' %>


<h2> <%= @blog.title %></h2>
<h3> <%= @blog.content %> </h3>

<%= link_to 'Edit', edit_blog_path(@blog)%>

<%= button_to 'delete', "/blogs/#{@blog.id}", method: :delete %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogChallenge</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>